DROP TABLE USUARIO IF EXISTS;

CREATE TABLE USUARIO (
    ID INTEGER PRIMARY KEY,
    EMAIL VARCHAR(64) NOT NULL,
    CPF CHAR(11) NOT NULL,
    -- SENHA??,
    NOME VARCHAR(64) NOT NULL,
    ENDERECO VARCHAR(64),
    TELEFONE VARCHAR(20),

    CONSTRAINT UNIQ_EMAIL UNIQUE(EMAIL),
    CONSTRAINT UNIQ_CPF UNIQUE(CPF),
);